name: Java CI with Maven

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      
      # Set up Java (specify the version you need)
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Build the project with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Upload the artifact (e.g., JAR file)
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-artifact
          path: target/*.jar

